name: CI

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 2: Build and start services
      - name: Build and start services
        run: docker-compose up --build -d

      - name: List running containers
        run: docker ps

      - name: Wait for MySQL to initialize
        run: sleep 15 # Adding a delay

      - name: Logs from cas_app
        run: docker logs cas_app

      - name: Logs from cas_db
        run: docker logs cas_db

      # Step 4: Upgrade database to head
      - name: Upgrade database
        run: docker exec cas_app alembic upgrade head

      # Step 5: Run tests
      - name: Run tests
        run: docker exec cas_app pytest --cov=src tests/

      # Step 6: Tear down services
      - name: Tear down services
        run: docker-compose down --volumes
