name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build and start services
      - name: Build and start services
        run: docker-compose up --build -d

      # Step 3: Downgrade database to base
      - name: Downgrade database
        run: docker-compose exec cas_app alembic downgrade base

      # Step 4: Upgrade database to head
      - name: Upgrade database
        run: docker-compose exec cas_app alembic upgrade head

      # Step 5: Run tests
      - name: Run tests
        run: docker-compose exec cas_app pytest tests/ -s -vv --tb=line

      # Step 6: Tear down services
      - name: Tear down services
        run: docker-compose down --volumes
