  name: CI

  on:
    push:
      branches:
        - main

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        # Step 1: Checkout the repository
        - name: Checkout repository
          uses: actions/checkout@v3

        # Step 2: Set up Docker Compose
        - name: Run tests using Docker Compose
          uses: adambirds/docker-compose-action@v1.5.0
          with:
            compose-file: "docker-compose.yaml"
            down-flags: "--volumes"  # Clean up volumes after tests
            test-container: "app"  # The service name in the docker-compose file
            test-command: |
              alembic downgrade base &&
              alembic upgrade head &&
              pytest tests/ -s -vv --tb=line  # Command to run migrations and tests
          env:
            MYSQL_USER: cas_user
            MYSQL_PASSWORD: cas_password
            MYSQL_DATABASE: cas_db
            MYSQL_HOST: db
            MYSQL_PORT: 3306
            ENV: "test"